"""add_user_machines_display_prefs

Revision ID: db7763314aba
Revises: 
Create Date: 2026-07-27 14:49:35.986900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db7763314aba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_machines_display_prefs',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('show_stat_cards', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('show_machine_cards', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.PrimaryKeyConstraint('user_id')
    )
    # 已有行必须带 server_default，否则 ADD COLUMN ... NOT NULL 会失败
    op.add_column('agents', sa.Column('net_errin', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('net_errout', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('net_dropin', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('net_dropout', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('net_errin_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('net_errout_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('net_dropin_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('net_dropout_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('tcp_retrans', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('tcp_retrans_rate', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('agents', 'public_ip',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agents', 'country_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agents', 'country',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agents', 'disk_total',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'disk_used',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'disk_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'net_sent_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'net_recv_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'net_bytes_sent',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'net_bytes_recv',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'tcp_connections',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'tcp_established',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.execute("UPDATE agents SET top_processes = '[]'::json WHERE top_processes IS NULL")
    op.alter_column('agents', 'top_processes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               server_default=sa.text("'[]'::json"))
    op.add_column('metrics', sa.Column('net_errin_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('metrics', sa.Column('net_errout_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('metrics', sa.Column('net_dropin_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('metrics', sa.Column('net_dropout_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('metrics', sa.Column('tcp_retrans_rate', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('metrics', 'disk_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('metrics', 'net_sent_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('metrics', 'net_recv_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('metrics', 'tcp_connections',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # TimescaleDB hypertable 常自带 time 索引，autogenerate 误检为多余；勿删除
    # op.drop_index(op.f('metrics_time_idx'), table_name='metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('metrics_time_idx'), 'metrics', [sa.literal_column('time DESC')], unique=False)
    op.alter_column('metrics', 'tcp_connections',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('metrics', 'net_recv_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('metrics', 'net_sent_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('metrics', 'disk_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('metrics', 'tcp_retrans_rate')
    op.drop_column('metrics', 'net_dropout_rate')
    op.drop_column('metrics', 'net_dropin_rate')
    op.drop_column('metrics', 'net_errout_rate')
    op.drop_column('metrics', 'net_errin_rate')
    op.alter_column('agents', 'top_processes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('agents', 'tcp_established',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'tcp_connections',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'net_bytes_recv',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'net_bytes_sent',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'net_recv_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'net_sent_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'disk_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'disk_used',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'disk_total',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'country',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agents', 'country_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agents', 'public_ip',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('agents', 'tcp_retrans_rate')
    op.drop_column('agents', 'tcp_retrans')
    op.drop_column('agents', 'net_dropout_rate')
    op.drop_column('agents', 'net_dropin_rate')
    op.drop_column('agents', 'net_errout_rate')
    op.drop_column('agents', 'net_errin_rate')
    op.drop_column('agents', 'net_dropout')
    op.drop_column('agents', 'net_dropin')
    op.drop_column('agents', 'net_errout')
    op.drop_column('agents', 'net_errin')
    op.drop_table('user_machines_display_prefs')
    # ### end Alembic commands ###
